from enum import Enum, unique


@unique
class ErrorCodes(Enum):
    REQUEST_VALIDATION_FAILED = 'VE400'
    INVALID_AUTHENTICATION = 'VE401'
    USER_NOT_FOUND = 'PO404'
    MULTIPLE_USERS_FOUND = 'PO409'
    INTERNAL_SERVER_ERROR = 'IS500'
    DATABASE_OPERATION_ERROR = 'PO111'
    GATEWAY_TIMEOUT = 'PO205'
